[package]
name = "livesort"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
description = "Print lines immediately then go back and sort them"
edition = "2018"
license = "Unlicense"
readme = "README"
repository = "https://git.sr.ht/~asayers/livesort"

[dependencies]
crossterm = "0.17"
